kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: nginx-app
  namespace: argocd-practice
spec:
  project: default
  source:
    repoURL: https://github.com/arpanelfranklin/argocd-demos.git
    targetRevision: main
    path: ui_approach/nginx
  destination: 
    server: http://44.255.61.211:8081
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
